# Generated by Django 5.1.15 on 2026-07-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='academic_group',
            field=models.CharField(blank=True, choices=[('first_cycle', 'First Cycle'), ('second_year', 'Second Year'), ('third_year', 'Third Year'), ('fourth_modeling', '4th Year — Modeling'), ('fourth_cryptology', '4th Year — Cryptology'), ('fourth_data_science', '4th Year — Data Science'), ('fourth_imm', '4th Year — IMM'), ('fifth_year', 'Fifth Year')], max_length=32),
        ),
    ]
