# Generated by Django 5.1.15 on 2026-07-31 14:02

import apps.accounts.models
from django.db import migrations, models


def assign_unique_codes(state_apps, schema_editor):
    """Give each existing user their own code — AddField applies one shared
    default value to all pre-existing rows."""
    User = state_apps.get_model("accounts", "User")
    for user in User.objects.all():
        user.recovery_code = apps.accounts.models.generate_recovery_code()
        user.save(update_fields=["recovery_code"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_academic_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recovery_code',
            field=models.CharField(default=apps.accounts.models.generate_recovery_code, editable=False, help_text='Secret code used (with the username) to reset a forgotten password.', max_length=20),
        ),
        migrations.RunPython(assign_unique_codes, migrations.RunPython.noop),
    ]
