# Generated by Django 5.1.15 on 2026-06-19 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('semester', models.PositiveSmallIntegerField(help_text='1–10 across the five years.')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['semester', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'semester'), name='unique_subject_per_semester')],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('course', 'Cours'), ('td', 'TD'), ('tp', 'TP'), ('summary', 'Résumé'), ('book', 'Livre'), ('other', 'Autre')], default='course', max_length=20)),
                ('drive_link', models.URLField(help_text='Google Drive (or similar) link.')),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_resources', to=settings.AUTH_USER_MODEL)),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='resources.subject')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='resources_r_status_f37b8d_idx')],
            },
        ),
    ]
