# Generated by Django 5.1.15 on 2026-06-19 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.PositiveSmallIntegerField(help_text='Year the exam was given, e.g. 2024.')),
                ('exam_type', models.CharField(choices=[('emd1', 'EMD 1'), ('emd2', 'EMD 2'), ('rattrapage', 'Rattrapage'), ('controle', 'Contrôle continu'), ('other', 'Autre')], default='emd1', max_length=20)),
                ('drive_link', models.URLField(help_text='Link to the exam paper (Google Drive).')),
                ('has_solution', models.BooleanField(default=False, help_text='A corrigé (solution) is available.')),
                ('solution_link', models.URLField(blank=True, help_text='Optional link to the corrigé.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_papers', to='resources.subject')),
            ],
            options={
                'ordering': ['-year', 'subject__semester', 'title'],
                'indexes': [models.Index(fields=['year'], name='resources_e_year_377e13_idx'), models.Index(fields=['exam_type'], name='resources_e_exam_ty_0a7087_idx')],
            },
        ),
    ]
