# Generated by Django 5.1.15 on 2026-06-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_exampaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='speciality',
            field=models.CharField(blank=True, choices=[('cryptology', 'Cryptology'), ('modeling', 'Modeling'), ('data_science', 'Data Science')], help_text='Required for S7–S10; leave blank for the S1–S6 common core.', max_length=20),
        ),
    ]
