# Generated by Django 5.1.15 on 2026-06-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_subject_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampaper',
            name='exam_type',
            field=models.CharField(choices=[('emd1', 'EMD 1'), ('emd2', 'EMD 2'), ('rattrapage', 'Rattrapage'), ('controle', 'Contrôle continu'), ('final', 'Final exam'), ('other', 'Autre')], default='emd1', max_length=20),
        ),
    ]
