# Generated by Django 5.1.15 on 2026-08-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_alter_subject_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='opens',
            field=models.PositiveIntegerField(default=0, help_text='Times the Drive link was opened (denormalised counter).'),
        ),
    ]
