# Generated by Django 5.1.15 on 2026-08-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestbookcomment',
            options={'ordering': ['-is_pinned', '-created_at']},
        ),
        migrations.AddField(
            model_name='guestbookcomment',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
