# Generated by Django 5.1.15 on 2026-08-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='label',
            field=models.CharField(blank=True, help_text='Custom activity name when no module is picked (e.g. Revision).', max_length=60),
        ),
    ]
