# Generated by Django 5.1.15 on 2026-07-11 15:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('title', models.CharField(blank=True, help_text='Field or role, e.g. Complex analysis.', max_length=120)),
                ('photo', models.ImageField(blank=True, upload_to='professors/')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide without deleting.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProfessorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.CharField(blank=True, max_length=280)),
                ('is_hidden', models.BooleanField(default=False, help_text='Hidden by an admin — excluded from the page and average.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='professors.professor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('professor', 'user'), name='one_rating_per_professor')],
            },
        ),
    ]
