# Generated by Django 5.1.15 on 2026-07-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professorrating',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Shown publicly only after an admin approves it (pre-moderation).'),
        ),
    ]
