# Generated by Django 5.1.15 on 2026-07-11 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0002_professorrating_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorrating',
            name='score',
            field=models.DecimalField(decimal_places=1, help_text='Any value from 0 to 5 (e.g. 3.5).', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
