# Generated by Django 5.1.15 on 2026-07-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0003_alter_professorrating_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='photo',
        ),
        migrations.AddField(
            model_name='professor',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Link to a photo (paste an image URL). Optional.'),
        ),
    ]
