# Generated by Django 5.1.15 on 2026-07-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0004_remove_professor_photo_professor_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professorrating',
            name='comment',
        ),
        migrations.AddField(
            model_name='professorrating',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Selected teaching-descriptor tags.'),
        ),
    ]
