# Generated by Django 5.1.15 on 2026-07-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.CharField(blank=True, max_length=200)),
                ('text_ar', models.CharField(blank=True, max_length=200, verbose_name='Arabic text')),
                ('link', models.URLField(blank=True, help_text='Optional link the item points to.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide without deleting.')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers show first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
